### PR TITLE
Fix NEMO_THREADED

### LINKED ISSUE #784: NEMO_THREADED=1 does not work
Setting NEMO_THREADED=1 in the environment before starting Julia does not cause Nemo to allow threading.

The reason is that __isthreaded is set outside of __init__ and is therefore hard coded at the time of the last precompilation. It is not changed by simply changing the environment and starting Julia again.

In order to set the value when Nemo is started up, independently of precompilation, it must be set in __init__

This is probably the case for NEMO_SOURCE_BUILD and any other flags we rely on for various things.

### PR DESCRIPTION
**Pull request by thofma**
Closes #784

### CODE REVIEW

File: src/Nemo.jl [hunk 1]
```diff
@@ -216,10 +214,15 @@ end
...
 ################################################################################
 
+const __isthreaded = Ref(false)
+
 function __init__()
    # In case libgmp picks up the wrong libgmp later on, we "unset" the jl_*
    # functions from the julia :libgmp.
-   if __isthreaded
+
+   __isthreaded[] =  "NEMO_THREADED" in keys(ENV) && ENV["NEMO_THREADED"] == "1"
```
Comment (rfourquet) [inline src/Nemo.jl]: While you are at it, you migth write it this way, which seems to be slighly faster in case the key is present:
```suggestion
   __isthreaded[] = get(ENV, "NEMO_THREADED", "") == "1"
```
