### PR TITLE
FiniteField from a poly: check that base ring is a field

### LINKED ISSUE #667: Segfault in FiniteField constructor with bad base ring
I typo'd the ResidueRing (1 instead of 2) and the subsequent `FiniteField` constructor segfaulted.
```
julia> R, x= ResidueRing(ZZ,1)["x"]
(Univariate Polynomial Ring in x over Integers modulo 1, 0)

julia> F = FiniteField(R(x^3+x^2+1), "z")

signal (11): Segmentation fault: 11
in expression starting at REPL[16]:1
fq_nmod_ctx_init_modulus at /Users/kfischer/.julia/dev/Nemo/deps/usr/lib/libflint.dylib (unknown line)
FqNmodFiniteField at /Users/kfischer/.julia/dev/Nemo/src/flint/FlintTypes.jl:1557
```

### PR DESCRIPTION
**Pull request by rfourquet**
The check can be bypassed with a check=false keyword argument.
Without a check, the result of calling FiniteField with a
non-field base ring ~~leads~~ can lead to to a segfault.

Fixes #667. Doc should still be added, and do the same for `fmpz_mod_poly`.

### CODE REVIEW

**Comment by wbhart** [comment]
The problem with this fix is that it checks primality of the same prime for *every* finite field constructed as an extension of the base ring.

It also prevents people researching primality testing algorithms, where primality of n is being checked by an algorithm they are developing. You are checking it for them and preventing them from constructing the object they need to construct for their algorithm. I'm not sure if this is a serious objection or not. But it does at least show that you won't get agreement on something like this.

**Comment by rfourquet** [comment]
> The problem with this fix is that it checks primality of the same prime for every finite field constructed as an extension of the base ring.

Yes, it seems to me like a sane default to choose correctness over speed. It's only a default though, and it's easy to pass the `check=false` keyword (or use a `ResidueField`).

> You are checking it for them and preventing them from constructing the object they need to construct for their algorithm.

Again, they can disable the check. But only courageous people or those knowing the internals would do that, as otherwise you create an object which assumes a field and you give it a non-field, who knows then the behavior when this assumption is broken? In the example from the issue, it simply segfaults, which is unacceptable by default. Without looking at the internals, I have no idea whether this will segfault for another modulus than 1.

File: src/flint/FlintTypes.jl [hunk 1]
```diff
@@ -1771,7 +1774,9 @@ mutable struct FqFiniteField <: FinField
       end
    end
 
-   function FqFiniteField(f::fmpz_mod_poly, s::Symbol, cached::Bool = true)
+   function FqFiniteField(f::fmpz_mod_poly, s::Symbol, cached::Bool = true; check::Bool = true)
+      check && !isprime(modulus(f)) &&
```
Comment (thofma) [inline src/flint/FlintTypes.jl]: We think that `isprime` is too expensive. Can you change this to `isprobable_prime` (or whatever the name is). Once this is done, we can merge this.

Comment (rfourquet) [reply src/flint/FlintTypes.jl]: Ok will do. Note that `isprime` is used in a couple other places in this file (`FlintPadicField` and `FlintQadicField`), would you like this to be changed too? (in a separate PR).

**Comment by wbhart** [comment]
If it is testing the primality of an fmpz (and not a small integer) and it is only preventing the user from doing something dumb, then yes, it should be changed there too.

**Comment by rfourquet** [comment]
> If it is testing the primality of an fmpz (and not a small integer) 

I inadvertently modified the two uses of `isprime` to `isprobable_prime` in this PR and got errors because in one case the argument was not `fmpz`. Would it make sense for you to extend `isprobable_prime` for some other types (e.g. defaulting to `isprime`) ?

**Comment by wbhart** [comment]
Yeah I don't recall if we define isprobable_prime for Int or UInt or both or neither.

Integer types are the only types it would make sense for, and there it is fine to default to isprime (so long as they are using Flint).

We definitely don't want to define isprime more generally, as isprime has a different meaning for other kinds of ring elements (unless we create a new function for that). (Well, there could be a couple of exceptions, but those are not important here.)

But in any case, we should be directly calling isprime, not isprobable_prime for anything up to 64 bits. That's because it takes no longer to certify primality in such cases then it does to check probable primality. This is because of large supercomputer projects that have verified there are no exceptions up to 2^64.

**Comment by wbhart** [comment]
There is an n_is_probprime in Flint (in the ulong_extras module) that we should probably call for isprobable_prime of Int and UInt. Feel free to add this function to Nemo if it doesn't exist. It's probably never been added because it isn't really useful anywhere, given how quickly Flint can prove primality up to 64 bits.

File: src/flint/fq.jl [hunk 2]
```diff
@@ -581,25 +581,27 @@ function FlintFiniteField(char::Integer, deg::Int, s::AbstractString; cached = t
 end
 
 @doc Markdown.doc"""
-    FlintFiniteField(pol::fmpz_mod_poly, s::AbstractString; cached = true)
+    FlintFiniteField(pol::PolyElem, s::AbstractString; cached = true, check = true)
```
Comment (wbhart) [inline src/flint/fq.jl]: I don't understand this change. It almost certainly won't work.

Comment (rfourquet) [reply src/flint/fq.jl]: I suppose it was to provide a more general documentation, as no docstring was attached to the version taking an `gfp_fmpz_poly`. But I agree `PolyElem` is too vague. I will add a note in the docstring specifying that this is currently only supported for `fmpz_mod_poly` and `gfp_fmpz_poly`.

Comment (rfourquet) [reply src/flint/fq.jl]: Ok, I removed this change because I can't build the documentation locally and test it. I will try to fix the failing doc build in another PR.

**Comment by wbhart** [comment]
I don't know which documentation issue you are talking about, but the FiniteField constructor is NOT generic. It does not need a more general function for documentation.

**Comment by rfourquet** [comment]
> but the FiniteField constructor is NOT generic.

No, but it accepts also a `gfp_fmpz_poly`, which is not documented, this is what I wanted to do. The same docstring can probably apply to both methods.

**Comment by wbhart** [comment]
I don't really see how. There is no common supertype for which the function makes sense. It's only valid for these two types. You could document it for the union (which has a name in FlintTypes), but I'm not sure that is really helpful to the user.

**Comment by rfourquet** [comment]
> I don't know which documentation issue you are talking about

Ok it was in my setting, in my "Nemo/docs project", `Nemo` was at version 15.1 instead of `dev`'ed, so it was erroring because of a not-found binding which was added later. Just saying in case you bump into the same problem.

> but I'm not sure that is really helpful to the user.

So I updated the docstring in #752, which have the signature applies to the union of the types. It's useful to the user to not read two times the same 6 lines of docstring in a row (e.g. online). When I see that as a user, I read both and try to find the little difference between the two texts to understand what differs between the two methods. So it's a waste of time if the two texts are the same.
