### PR TITLE
Fix `MPoly` constructors to enforce exponents being nonnegative

### LINKED ISSUE #2276: Negative exponents for MPolys
In the context of https://github.com/Nemocas/AbstractAlgebra.jl/pull/2385 I found a problem with negative exponents in Nemo:

```julia
julia> R,(x,y)=ZZ[:x,:y];

julia> R([ZZ(1)], [[ZZ(-1), ZZ(0)]])
x

julia> R([ZZ(1)], [[-1, 0]])
x^18446744073709551615
```

In the case of negative ZZRingElems the sign is ignored and in the case of negative Ints the actual bits of the Ints are interpreted as a UInt. I think both should just raise an error. What do you think?

### PR DESCRIPTION
**Pull request by SoongNoonien**
Fixes #2276.
One of the checks is redundant because the `FpMPolyRingElem` function is defined for a union of exponent types including `UInt` which will never contain negative values. Perhaps all constructors should be restructured to follow a common pattern?

### CODE REVIEW

**Review by lgoettgens — COMMENTED** [review]
Better use `is_positive` as that will generate better code in julia 1.13 and later. In particular, that check should then compile away for UInt.

**Comment by SoongNoonien** [comment]
I think we would rather need `is_nonnegative` here which is not defined for `ZZRingElem` yet.

**Comment by lgoettgens** [comment]
You can use `!is_negative`

**Comment by SoongNoonien** [comment]
Thanks, didn't think of it.

File: src/flint/FlintTypes.jl [hunk 1]
```diff
@@ -1123,6 +1123,7 @@ mutable struct ZZMPolyRingElem <: MPolyRingElem{ZZRingElem}
   end
 
   function ZZMPolyRingElem(ctx::ZZMPolyRing, a::Vector{ZZRingElem}, b::Vector{Vector{Int}})
+    @req all(x -> !any(is_negative.(x)), b) "Negative exponents are not allowed"
```
Comment (lgoettgens) [inline src/flint/FlintTypes.jl]:
```suggestion
    @req all(x -> all(!is_negative, x), b) "Negative exponents are not allowed"
```
I did mean it exactly like I wrote it. You could've just replaced the `>=(0)` by `!is_negative`

Comment (SoongNoonien) [reply src/flint/FlintTypes.jl]: Ah, I didn't know this was possible. Thanks!

**Review by lgoettgens — APPROVED** [review]
