### PR TITLE
Restructure `evaluate` for mpolys

### LINKED ISSUE #2180: Evaluating polynomials with zero variables gives error
```julia
using Nemo
R, () = polynomial_ring(QQ, Symbol[])
x = one(R)
evaluate(x, [])
```

gives the following error:

```shell
ERROR: BoundsError: attempt to access 0-element Vector{QQMPolyRingElem} at index [1]
Stacktrace:
 [1] throw_boundserror(A::Vector{QQMPolyRingElem}, I::Tuple{Int64})
   @ Base ./essentials.jl:15
 [2] getindex
   @ ./essentials.jl:919 [inlined]
 [3] evaluate(a::QQMPolyRingElem, bs::Vector{QQMPolyRingElem})
   @ Nemo ~/.julia/packages/Nemo/kdloy/src/flint/fmpq_mpoly.jl:600
 [4] evaluate(a::QQMPolyRingElem, vals::Vector{Any})
   @ AbstractAlgebra ~/.julia/packages/AbstractAlgebra/T6WZD/src/MPoly.jl:862
 [5] top-level scope
   @ REPL[5]:1
```

while `evaluate(x, QQFieldElem[])` gives the desired result.

Indeed, in the functions below, `S = parent(bs[1])` fails when `bs` is empty...

https://github.com/Nemocas/Nemo.jl/blob/f9ccb665709d525e6de6b04a675e3d95be99ce54/src/flint/fmpq_mpoly.jl#L598-L624

### PR DESCRIPTION
**Pull request by SoongNoonien**
This is a work in progress towards https://github.com/Nemocas/AbstractAlgebra.jl/issues/2225 and https://github.com/Nemocas/Nemo.jl/issues/2180. At the moment this introduces some method ambiguities which need to be resolved first. I think if I readjusted this PR to make the `f(...)` syntax the default I should be able to resolve them without a new AbstractAlgebra release.

Note that I started with the `fmpq` mpolys and that the other mpoly types of Nemo are still missing.

Edit: fixes #2180

### CODE REVIEW

**Comment by SoongNoonien** [comment]
> What do you mean by that? Let `evaluate` call `f(...)` and let that do the actual work?

Yes.

> Personally I am not a great fan, I prefer if such "syntactic sugar" functions stay to their minimum. Alas, that's just my base feeling, if there are technical arguments, I am all ears.

Yes, I'd say so too. But in AbstractAlgebra it is done that way (i.e. `evaluate` calls `f(...)`) unfortunately.

File: src/flint/fmpz_mpoly.jl [hunk 1]
```diff
@@ -534,7 +534,8 @@ end
 ###############################################################################
 
 function evaluate(a::ZZMPolyRingElem, b::Vector{ZZRingElem})
-  length(b) != nvars(parent(a)) && error("Vector size incorrect in evaluate")
+  iszero(length(b)) && error("need at least one value")
+  length(b) != nvars(parent(a)) && error("Number of variables does not match number of values")
```
Comment (thofma) [inline src/flint/fmpz_mpoly.jl]: Maybe we can start using `@req` for this

Comment (SoongNoonien) [reply src/flint/fmpz_mpoly.jl]: Yes, of course. I'd like to address all of these checks in the evaluate functions while on it.
