### PR TITLE
QQBar: Add 'missing' guess methods, constructors

### LINKED ISSUE #1388: Unexpected error for `guess`
The documentation gives this example:
```
julia> RR = ArbField(128);

julia> x = RR(0.1);       # note: 53-bit binary approximation of 1//10 without radius

julia> guess(QQBar, x, 1)
Root 0.100000 of 36028797018963968x - 3602879701896397

julia> guess(QQBar, x + RR("+/- 1e-10"), 1)
Root 0.100000 of 10x - 1
```

What we actually get is
```
julia> guess(QQBar, x, 1)
ERROR: No suitable algebraic number found
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:33
 [2] guess(R::CalciumQQBarField, x::acb, maxdeg::Int64, maxbits::Int64)
   @ Nemo ~/Projekte/OSCAR/Nemo.jl/src/calcium/qqbar.jl:1246
 [3] guess
   @ ~/Projekte/OSCAR/Nemo.jl/src/calcium/qqbar.jl:1273 [inlined]
 [4] guess(R::CalciumQQBarField, x::arb, maxdeg::Int64)
   @ Nemo ~/Projekte/OSCAR/Nemo.jl/src/calcium/qqbar.jl:1272
 [5] top-level scope
   @ none:1
```

I am not sure if the example is wrong or if this is a regression?

Background: I am rewriting many examples into `jldoctest` right now, which uncovered various minor issues.

### LINKED ISSUE #1649: Add missing conversion `QQBarFieldElem` -> `RealFieldElem` / `ComplexFieldElem`
We have conversion to `ArbField` and `AcbField` but not the others. Probably no deeper reason other than "forgot to add them when the implementations split.

Example:
```
julia> x = sqrt(QQBar(2))
Root 1.41421 of x^2 - 2

julia> RR = ArbField(64); RR(x)
[1.414213562373095049 +/- 3.45e-19]

julia> RR = RealField(); RR(x)
ERROR: MethodError: no method matching (::RealField)(::QQBarFieldElem)
```

### PR DESCRIPTION
**Pull request by fingolfin**
Also de-duplicate 'guess' docstring.

Resolves #1388
Resolves #1649

### CODE REVIEW

File: src/calcium/qqbar.jl [hunk 1]
```diff
@@ -1337,6 +1337,9 @@ end
 
 @doc raw"""
     guess(R::QQBarField, x::AcbFieldElem, maxdeg::Int, maxbits::Int=0)
+    guess(R::QQBarField, x::ArbFieldElem, maxdeg::Int, maxbits::Int=0)
+    guess(R::QQBarField, x::RealFieldElem, maxdeg::Int, maxbits::Int=0)
+    guess(R::QQBarField, x::ComplexFieldElem, maxdeg::Int, maxbits::Int=0)
```
Comment (lgoettgens) [inline src/calcium/qqbar.jl:1342]:
```suggestion
    guess(R::QQBarField, x::ComplexFieldElem, maxdeg::Int, maxbits::Int=0)
    guess(R::QQBarField, x::RealFieldElem, maxdeg::Int, maxbits::Int=0)
```

**Review by lgoettgens — APPROVED** [review]
