### PR TITLE
Fix div/divrem

### LINKED ISSUE #743: *Massive* regression in nf_elem adhoc binary tests
The tests are taking waaaaay longer than they were. Either there has been a massive regression in the AbstractAlgebra/Nemo library code or the tests have been modified in a way that makes them take forever.

If anyone knows what it is, could you please make a PR to fix it. I don't see anything obvious, except for the fact that it does 100 tests for each of a pile of explicit primes. I don't know if this is how it used to be or if it has been changed recently.

Just lowering the number of iterations here is not enough. We need to track down the actual source of the regression and once it is understood, fix it.

### LINKED ISSUE #842: Modules over Nemo.ZZ fail due to divrem/div definitions
AbstractAlgebra internally defines div/divrem differently to Julia for Julia integer types (to agree with mod not rem, so that there's a minimal set of representatives mod n).

This means that the AbstractAlgebra tests for modules over ZZ will pass, but when they are run for modules over ZZ using Nemo, they will fail, as Nemo does not internally define div/divrem in the same way AbstractAlgebra does, but continues to use the Julia definitions.

```
julia> using Nemo

Welcome to Nemo version 0.17.5

Nemo comes with absolutely no warranty whatsoever

julia> import AbstractAlgebra

julia> function rand_module(R::AbstractAlgebra.Ring, vals...)
          rk = rand(0:5)
          M = FreeModule(R, rk)
          levels = rand(0:3)
          for i = 1:levels
             if ngens(M) == 0
                break
             end
             G = [rand(M, vals...) for i in 1:rand(1:ngens(M))]
                   S, f = sub(M, G)
             if rand(1:2) == 1
                M, f = quo(M, S)
             else
                M = S
             end
          end
          return M
       end
rand_module (generic function with 1 method)

julia> for R in [ZZ, QQ]
             for iter = 1:100
                M = rand_module(R, -10:10)

                I, f = snf(M)

                K, g = kernel(f)

                         @test length(invariant_factors(K)) == 0

                m = rand(I, -10:10)

                @test m == inv(f)(f(m))
                      end
          end
Test Failed at REPL[17]:13
  Expression: m == (inv(f))(f(m))
   Evaluated: (-1, -3) == (1, -3)
ERROR: There was an error during testing
```

The test is taken from AbstractAlgebra's test/generic/InvariantFactorDecomposition-test.jl.

The correct fix for this is not to define div/divrem for fmpz differently to Julia (we already agreed they should concur with Julia's definition) but to do the following:

* do not import div/divrem from Base in Nemo
* export the current definitions of div/divrem for fmpz in Nemo as Base.div and Base.divrem only (so that this is what the user of Nemo will see) (*)
* define div/divrem *inside* Nemo to agree with the internal AbstractAlgebra definitions for Julia integers (which agree with mod not rem); these must extend AbstractAlgebra.div/divrem
* import Nemo.div/divrem not Base.div/divrem in Oscar (**)
* fix all the bugs in Nemo/Hecke/Oscar that arise as a result of this change
* write up some developer documentation somewhere that explains this (***)

### PR DESCRIPTION
**Pull request by wbhart**
This makes the internal definition of div/divrem in Nemo agree with the internal definition used by AbstractAlgebra (and with Flint).

This allows generic code to run correctly over Nemo.fmpz (e.g. the Generic.Modules test that I added as a regression test).

Fixes #842 
Fixes #743 (because it was annoying me)

N.B. This is breaking and should not be merged until we have checked that no other packages break. In any event, at least Hecke.jl and Oscar.jl (and maybe Singular.jl) should import Nemo.div and Nemo.divrem instead of Base.div and Base.divrem, which will likely cause breakage.

I will check this out as soon as possible.

### CODE REVIEW

**Comment by thofma** [comment]
Does this mean `Base.div(::fmpz, ::fmpz)` and `Nemo.div(::fmpz, ::fmpz)` are different? So in `Nemo` and in the REPL the behaviors are different? Sorry, but this will be a no from my part. This makes working with the only useful integer type that we have more cumbersome, just to cope with some questionable design desicions for `BigInt`, which no one should use anyway.

**Comment by thofma** [comment]
Let's continue this at #842.

**Comment by wbhart** [comment]
It's already different in AbstractAlgebra.

I have opened many tickets discussion possible solutions to this problem. There aren't really any options left.

File: src/Nemo.jl [hunk 1]
```diff
@@ -423,6 +426,16 @@ const FiniteField = FlintFiniteField
...
 
+###############################################################################
+#
+#   Internal/External definitions
+#
+###############################################################################
+
+div(a, b) = Base.div(a, b)
+
+divrem(a, b) = Base.divrem(a, b)
```
Comment (thofma) [inline src/Nemo.jl:437]: If I understand correctly, should this not be in AbstractAlgebra?

Comment (wbhart) [reply src/Nemo.jl:437]: It might still work if we move it there. I am really not sure.

The purpose of it is so that Nemo's version of divrem, will use the Base definition (which we have defined in Nemo) when there isn't something more specific defined (e.g. fmpz).

For example, we define Base.div for power series in Nemo (because we can't export Nemo's div to the user any other way). In order for Nemo to use that same definition internally, these redirect it to there.

Comment (thofma) [reply src/Nemo.jl:437]: I see. But this redirect should also be done for all non-`BigInt` types in AbstractAlgebra I think, and this should cover also all that is happening here in Nemo. We are already doing it here:
https://github.com/Nemocas/AbstractAlgebra.jl/blob/6fa064a1e5cc8eabbb549fcbeae20055e0fac13a/src/AbstractAlgebra.jl#L64-L70

Comment (wbhart) [reply src/Nemo.jl:437]: In answer to your question: no. These are already in AbstractAlgebra, and they don't work for Nemo when they are only there.

On the other hand it's possible that another change I made makes them redundant. I'll try removing them and see if the tests still pass.

Comment (thofma) [reply src/Nemo.jl:437]: If they don't work, then something is off I would say. If you remove them in Nemo, what does `@which AbstractAlgebra.divrem(fmpq(1), fmpq(1))` say?

Comment (wbhart) [reply src/Nemo.jl:437]: In fact the tests pass if I remove these two. I think I wasn't overloading the AbstractAlgebra definitions previously, which is why I inserted these. Now that I'm doing that, these are actually redundant, it seems. I'll remove them and push momentarily.

Comment (wbhart) [reply src/Nemo.jl]: Fixed.

**Comment by thofma** [comment]
I will make a new patch release with the new flint version (once it is merged upstream) and then we can merge this here.
