### PR TITLE
Fix calls to InexactError.

### LINKED ISSUE #702: No method matching InexactError()
The following code will trigger this error:

```
Int(ZZ(479732498732498732498732492384798327498723))
```

Julia have changed their InexactError since we started using it, and we have not updated all our uses of it.

### PR DESCRIPTION
**Pull request by wbhart**
Closes #702

### CODE REVIEW

File: src/flint/FlintTypes.jl [hunk 1]
```diff
@@ -48,7 +48,7 @@ mutable struct fmpz <: RingElem
     end
 
     function fmpz(x::Float64)
-        !isinteger(x) && throw(InexactError())
+        !isinteger(x) && throw(InexactError(:convert, fmpz, x))
```
Comment (rfourquet) [inline src/flint/FlintTypes.jl]: You could also write `InexactError(:fmpz, fmpz, x))`, and then the message will be something like `InexactError: fmpz(1.1)`.

Comment (wbhart) [reply src/flint/FlintTypes.jl]: unfortunately that does not seem to be the case, at least not in Julia 1.

Comment (rfourquet) [reply src/flint/FlintTypes.jl]: Ah right sorry, it starts to have this behavior in Julia 1.1 ... I find the API of this `InexactError` function weird in any case.
