### PR TITLE
fix: lll_gram for negativ definit matrices

### LINKED ISSUE #2216: Error in `lll_gram_with_transform`: unknown function `neg`
```
function lll_gram_with_transform(x::ZZMatrix, ctx::LLLContext = LLLContext(0.99, 0.51, :gram))
  @req is_square(x) && is_symmetric(x) "The matrix must be a symmetric square matrix"
  # try to recognize the definite case
  if nrows(x) == 0
    return x, x
  end
  if _is_definitely_full_rank(x)
    u = identity_matrix(ZZ, nrows(x))
    if x[1, 1] < 0
      y = neg(x)     # <---  HERE
      _lll_gram_with_transform!(y, u, ctx)
      return neg!(y), u
    else
```

Perhaps `neg!` was meant?

Clearly this code is not exercised by anything, perhaps we can add a test case?

Found by JET

### PR DESCRIPTION
**Pull request by thofma**
Closes #2216.

### CODE REVIEW

File: src/flint/fmpz_mat.jl [hunk 1]
```diff
@@ -1122,7 +1122,7 @@ function lll_gram!(x::ZZMatrix, ctx::LLLContext = LLLContext(0.99, 0.51, :gram))
   # try to recognize the definite case
   if _is_definitely_full_rank(x)
     if x[1, 1] < 0
-      return neg!(_lll_gram!(!neg(x), ctx))
+      return neg!(_lll_gram!(neg!(x), ctx))
```
Comment (fingolfin) [inline src/flint/fmpz_mat.jl:1125]: oh fun, good that you caught this one, too :-)

**Review by fingolfin — APPROVED** [review]
