### PR TITLE
Fix interpolation

### LINKED ISSUE #322: Interpolation over a non-integral domain
Using interpolation for determinant of a matrix over a polynomial ring is problematic, since if the coefficient ring has zero divisors the result of the interpolation may not even be unique, or at the very least we no longer raise an exception when doing division if the leading coefficient is not invertible.

The problem is, detecting whether we have zero divisors or not may be expensive, and the result may be incorrect if we don't detect this.

### PR DESCRIPTION
**Pull request by wbhart**
This fixes #322 by introducing an isdomain_type function which tells whether only domains can be implemented by the given type. Generic interpolation is now only valid over such types. We also support generic interpolation over residue rings, so long as we don't hit impossible inverses.

This doesn't support rings such polynomial rings over R = Z[x]/(x+1)^3 where elements in R can be non-invertible without being zero divisors, e.g. 2. However, polynomials over R are not currently supported in Nemo anyway due to the lack of a mod function, so if we eventually support this ring, we will have to also support interpolation over it separately.

### CODE REVIEW

File: src/Rings.jl [hunk 1]
```diff
@@ -137,6 +137,15 @@ isexact(R::Ring) = true
 
 ###############################################################################
 #
+#   isdomain_type
+#
+###############################################################################
+
+# Rings are not domain types unless explicitly specified
+isdomain_type(R::RingElem) = true
```
Comment (thofma) [inline src/Rings.jl]: According to the comment it should be `false` instead of `true`.

**Comment by wbhart** [comment]
Good catch. I'll fix it.
