### PR TITLE
Fix div, rem, divrem and mod and adhoc versions #688.

### LINKED ISSUE #688: mod(a, -b) does not agree with Julia/AbstractAlgebra
When the modulus is negative, Nemo always returns a positive remainder. This is inconsistent with what Julia or AbstractAlgebra does. We should switch to the Julia definition.

For example, mod(2, -3) returns -1 in Julia and 2 in Nemo. The Julia definition is better because if a = 2 and m = -3 we have:

a = mq + r where q = -1 and r is between 0 and m.

And just for fun:

```
mod(ZZ(2), -3)
```

currently returns 0ffffffffffffffff which wouldn't be my favourite answer.

### LINKED ISSUE #689: mod(ZZ(2), ZZ(0)) is entertaining
I recommend running it, before fixing it, just for the entertainment.

### PR DESCRIPTION
**Pull request by wbhart**
These changes should only affect the results if the modulus is negative. They should now agree with Julia.

Closes #688 

Closes #689  (inadvertently).

### CODE REVIEW

File: src/flint/fmpz.jl [hunk 1]
```diff
@@ -407,8 +407,11 @@ divexact(x::Integer, y::fmpz) = divexact(fmpz(x), y)
 
 function rem(x::fmpz, c::Int)
     c == 0 && throw(DivideError())
-    r = ccall((:fmpz_tdiv_ui, :libflint), Int, (Ref{fmpz}, Int), x, abs(c))
-    return sign(x) > 0 ? r : -r
+    q = fmpz()
+    r = fmpz()
+    ccall((:fmpz_tdiv_qr, :libflint), Nothing,
+          (Ref{fmpz}, Ref{fmpz}, Ref{fmpz}, Ref{fmpz}), q, r, x, fmpz(c))
+    return r
```
Comment (rfourquet) [inline src/flint/fmpz.jl]: `rem(x::fmpz, c::Int) = rem(x, fmpz(c))`
